[package]
name = "tingle"
version = "0.1.0"
readme = "README.md"
license = "MPL-2.0"
authors = ["James Laver <james.laver@gmail.com>"]
edition = "2018"

[features]
default = ["smol"]

[dependencies]
async-channel="1.1.1"
concurrent-queue="1.1.1"
futures-core = "0.3"
intmap = "0.7"
pin-project-lite = "0.1"

[dependencies.smol]
version = "0.1"
optional = true

[dev-dependencies]
futures = "0.3"
smol = "0.1"