[package]
name = "tingle"
version = "0.1.0"
readme = "README.md"
license = "MPL-2.0"
authors = ["James Laver <james.laver@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
event-listener = "2.2"
intmap = "0.7"
pin-project-lite = "0.1"

[dev-dependencies]
futures = "0.3"
smol = "0.1"