[package]
name = "async-backplane"
version = "0.1.0"
readme = "README.md"
license = "MPL-2.0"
authors = ["James Laver <james.laver@gmail.com>"]
edition = "2018"

[features]
default = ["smol"]
nightly = []

[dependencies]
async-channel = "1.1"
concurrent-queue = "1.1"
futures-lite = "0.1.5"
intmap = "0.7"
maybe-unwind = "0.3"
# smallvec = "1.4"
pin-project-lite = "0.1"
# primitive_traits = "0.2"

[dependencies.rw-lease]
path = "../rw-lease"
# git = "https://github.com/irrustible/rw-lease"
# branch = "main"
# version = "0.1"
default-features = false

[dependencies.smol]
version = "0.2"
optional = true

