[package]
name = "tingle"
version = "0.1.0"
authors = ["James Laver <james.laver@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [dev-dependencies]
# criterion = "0.3"
# rand_xoshiro = "0.4"
# rand_core = "0.5"

[dependencies]
# async-task = "1.3"
# once_cell = "1.3"
# crossbeam = "0.7"
futures = "0.3"
maybe-unwind = "0.2" # getting more information out of stack unwinds in tests

im = "14.3"

# concurrency

# pinning
# pin-cell = "0.1.1"
pin-project = "0.4"
# pin-utils = "0.1.0-alpha.4"

# errors - hard pinned, dtolnay has a habit of breaking things
anyhow = "1.0.28"
thiserror = "1.0.14"

# [dependencies.tokio]
# version = "0.2"
# features = ["full"]

[dependencies.global_counter]
git = "https://github.com/LukiRe/global_counter"
branch = "master"

# [dependencies.async-std]
# version = "1.5.0"

# [[bench]]
# name = "crossbeam"
# harness = false
