[package]
name = "tingle"
version = "0.1.0"
readme = "README.md"
license = "MPL-2.0"
authors = ["James Laver <james.laver@gmail.com>"]
edition = "2018"

[dependencies]
event-listener = "2.0"
futures = "0.3"
intmap = "0.7"
fastrand = "1.1"
piper = "0.1"

[dev-dependencies]
smol = "0.1"