[package]
name = "tingle"
version = "0.1.0"
readme = "README.md"
license = "MPL-2.0"
authors = ["James Laver <james.laver@gmail.com>"]
edition = "2018"

[features]
default = ["smol"]

[dependencies]
async-channel = "1.1"
concurrent-queue = "1.1"
futures-core = "0.3"
intmap = "0.7"
maybe-unwind = "0.3"

[dependencies.rw_lease]
# path = "../rw_lease"
git = "https://github.com/irrustible/rw_lease"
branch = "main"
# version = "0.1"

[dependencies.smol]
version = "0.1"
optional = true

[dev-dependencies]
futures = "0.3"
smol = "0.1"