[package]
name = "tingle"
version = "0.1.0"
authors = ["James Laver <james.laver@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [dev-dependencies]
# criterion = "0.3"
# rand_xoshiro = "0.4"
# rand_core = "0.5"


[features]
default = ["smol"]

[dependencies]
# async-task = "1.3"
# once_cell = "1.3"
# crossbeam = "0.7"
# im = "14.3"
intmap = "0.7.0"

# tracing = "0.1"
futures = "0.3"
# maybe-unwind = "0.2" # getting more information out of stack unwinds in tests

piper = {git = "https://github.com/stjepang/piper"}

# errors - hard pinned, dtolnay has a habit of breaking things
anyhow = "1.0.28"
thiserror = "1.0.14"

[dependencies.smol]
path = "../smol"
optional = true

[dependencies.tokio]
version = "0.2"
features = ["time"]
default-features = false
optional = true

[dependencies.async-std]
version = "1.5"
# features = ["time"]
default-features = false
optional = true